name: Continuous integration
on: push
jobs:
  checkstyle:
    name: Java Code Check Style
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: checkstyle
        run:
          bash $(pwd)/mall-scripts/ci/checkstyle.sh $(pwd)
  findbugs:
    name: Java Code Find Bugs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: findbugs
        run: bash ./mall-scripts/ci/findbugs.sh